window.x = 375;
window.y = 400;
window.moveX = 0;
window.moveY = 0;
window.xOfC;
window.yOfC;
window.xOfFirstTriangle;
window.speedOfC;
window.pauseTime;
window.backgroundColor;
window.fontColor = [255, 255, 255, 255];
window.playerColor;
window.colorOfC;
window.removeAvoidC = false;
window.addAble = true;
window.nextLevelAnim = false;
window.timer = 0;
window.nextLevel = 1200;
window.xOfInterval = -400;
window.gameOver = false;
window.gameOverBackGroundColor = [0, 0, 0, 0];
window.boxShadowColor = [0, 0, 0, .7];
window.gameOverText = 0;
window.reStartButtonColor = [255, 255, 255];
window.dieAble = true;